# Case

Naive sentiment analysis

This is a simple project using Naive Bayes Classifier and Scikit-learn to create a Google Play store reviews classifier (Sentiment Analysis) in Python. You will categorize user reviews as good or bad. The Naive Bayes classification technique is a simple and powerful classification task in machine learning. The Naive Bayes classification technique is a simple and powerful classification task in machine learning. In this dataset, we use the 23 most popular mobile apps, and only two columns.

Step 1:

We have three columns: package name, review and polarity (0 = bad, 1 = good) Preprocess the data by eliminating the package name column and putting all reviews in lower case.

Step 2:

Separate target from feature, and split your data.

Step 3:

Vectorize your features and use Naive Bayes to classify the reviews as good or bad. We will not focus on hypertuning our model this time. This was an introduction project to sentiment analysis using Naive Bayes.

Step 4:

Use the app.py to create your pipeline.

Save your naive bayes classification model in the 'models' folder.

Insall de libraries

In [52]:
!pip install pandas
!pip install numpy
!pip install sklearn
!pip install nltk
%pip install pickle


[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Imports

In [53]:
import pandas as pd
import numpy as np
import nltk #text processing
import re
import unicodedata
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

In [54]:
#load the words to use as filter
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/gitpod/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

Load Data of Reviews

In [55]:
url='https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews_dataset.csv'
df = pd.read_csv(url)

Explore Dataset

In [56]:
df.head()


package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [57]:
df['polarity'].value_counts()

0    584
1    307
Name: polarity, dtype: int64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   package_name  891 non-null    object
 1   review        891 non-null    object
 2   polarity      891 non-null    int64 
dtypes: int64(1), object(2)
memory usage: 21.0+ KB


Package name, review and polarity (0 = bad, 1 = good)

In [59]:
df.sample(10)

package_name  \
407           com.facebook.orca   
660           com.hamrokeyboard   
216  com.supercell.clashofclans   
429           com.facebook.orca   
108        com.linkedin.android   
217  com.supercell.clashofclans   
367     com.google.android.talk   
587                com.evernote   
28          com.facebook.katana   
714       com.opera.mini.native   

                                                review  polarity  
407    sometimes, if i turn off wifi, both messenge...         0  
660   cannot use properly ालाई चाहि...         0  
216   nyc  1 u guys should apply some same strategy...         0  
429   linda cooper hardy it is essential at times, ...         0  
108   not able send requests to connect not able to...         0  
217   it was epic....then a certain update happened...         0  
367   would like to see who are currently online? p...         0  
587   ever so useful evernote it is so easy to 'scr...         1  
28    you should fix this it does'nt work anymore. ...         0  
714    for the build 13.0.2036.98649  new colour sc...         0


Text Processing - Clean

Step 1 - change all to lower case


In [60]:
#Preprocess the data by eliminating the package name column and putting all reviews in lower case.

df.drop(['package_name'],axis=1, inplace=True)
#chante all to lower case
df['review'] = df['review'].str.lower()




Step 2 - Remove all words that not have meaning to the search - stop words


In [61]:
#see, the word in the reviews, create a list of word and frecuency
df['review'].str.split(expand = True).stack().value_counts()[:60] #(show top 60)

the       1293
to        1159
i         1084
and        853
it         778
a          619
is         555
my         442
this       421
for        410
of         390
but        348
in         340
on         325
not        318
app        317
you        315
that       260
have       252
with       220
so         203
be         194
no         186
when       182
if         180
or         169
all        163
can        158
as         148
me         145
are        139
it's       138
can't      137
update     136
new        136
like       135
fix        133
please     131
good       128
game       121
one        119
use        118
just       117
get        112
its        111
very       109
more       107
was        104
there      104
don't      103
now        102
will       102
even       101
from       101
at         100
up          99
great       99
time        93
your        90
do          89
dtype: int64

In [62]:
#remove the stopword
stop = stopwords.words('english')

def remove_stopwords(text):
  if text is not None:
    #list of the word in the text
    words = text.strip().split()
    words_filtered = []
    for word in words:
      if word not in stop:
        words_filtered.append(word)
    result = " ".join(words_filtered) #join the word in a text with space separation
  else:
      result = None
  return result




Eliminamos los caracteres desconocidos


In [63]:
df['review']=df['review'].str.strip()
df['review']=df['review'].str.lower()

In [64]:
def normalize_str(text_string):
    if text_string is not None:
        result=unicodedata.normalize('NFD',text_string).encode('ascii','ignore').decode()
    else:
        result=None 
    return result

In [65]:
df['review']=df['review'].apply(normalize_str)
df['review']=df['review'].str.replace('!','')
df['review']=df['review'].str.replace(',','')
df['review']=df['review'].str.replace('&','')
df['review']=df['review'].str.normalize('NFKC')
df['review']=df['review'].str.replace(r'([a-zA-Z])\1{2,}',r'\1',regex=True)

In [66]:
df.sample(10)

review  polarity
2    profile any time my wife or anybody has more t...         0
432  doesn't send the message i have an active inte...         0
388  mms failure still have issues with group messa...         0
858  great fun. very addictive. still brilliant loa...         1
231  update sucks i have some friends who didn't pl...         0
59   good ui ux and helpful in governance looking t...         0
482  works fine for the most part. not sure why it ...         1
304  forgot my old wechat password i want to reopen...         0
117  app requires frequent login password why the h...         0
702  easy to play and always running jumping and de...         1

In [67]:
df.iloc[675,]

review      loved it rzrl app rrlrrl rrsrzrlrrl r rrsrzrlr...
polarity                                                    1
Name: 675, dtype: object

In [68]:
df_interim = df.copy()

In [69]:
df_interim['review'] = df_interim['review'].apply(remove_stopwords)


In [70]:
df_interim['review'].str.split(expand=True).stack().value_counts()[:60] 

app         351
update      150
game        140
please      138
like        137
can't       137
new         137
fix         135
good        134
use         123
one         120
great       115
get         112
even        102
time         98
browser      85
really       84
back         81
still        80
would        80
love         77
make         74
5            71
work         71
also         69
see          69
using        68
phone        68
i'm          67
open         66
it.          65
want         64
google       64
much         62
every        61
version      60
option       59
u            58
way          57
app.         56
go           56
android      56
used         55
best         54
download     53
better       53
play         52
.            51
give         50
send         49
people       48
able         48
message      47
since        47
many         46
works        45
apps         45
ads          45
keep         45
old          44
dtype: int64

In [71]:
def word_only_letters(word):
    for c in word:
        cat = unicodedata.category(c)
        if cat not in ('Ll','Lu'):  #only letter upper y lower
            return False
    return True

# clean only letter
def text_only_letters(text):
    if text is not None:
        #list of the word in the text
        words = text.strip().split()
        words_filtered = []
        for word in words:
            if word_only_letters(word):
                words_filtered.append(word)
            result = " ".join(words_filtered) #join the word in a text with space separation
    else:
        result = None
    return result

In [72]:
df_interim['review'] = df_interim['review'].apply(text_only_letters)

In [73]:


#remove multi letter looove iiiitttt, or repeat secuence
def replace_multiple_letters(message):
  if message is not None:
    result = re.sub(r'(.+?)\1+', r'\1', message)
    #result = re.sub(r"([a-zA-Z])＼1{2,}", r"＼1", message)
  else:
    result = None
  return result


In [74]:
df_interim['review'] = df_interim['review'].apply(replace_multiple_letters)

In [75]:
df_interim['review']

0      privacy least put option apear mean people lik...
1      mesenger isues ever since last update initial ...
2      profile time wife anybody one post view would ...
3      new features suck us working back buton guys m...
4      forced reload uploading pic replying coment la...
                             ...                        
886    loved incredible awesome go power make new cla...
887    time legendary game birthday party levels shor...
888    ads way heavy listen bad ads every round wheth...
889    fun works perfectly ads anoying think especial...
890    everywhere se angry birds everywhere stop play...
Name: review, Length: 891, dtype: object

In [76]:
#copy to df
df = df_interim.copy()




Setp 3 - Model


In [77]:
# Separate target and predictor
X = df['review']
y = df['polarity']


In [78]:
X=df['review']
y=df['polarity']

In [79]:
#Split your data in train and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=42) #, test_size=0.25

In [80]:
#Vectorizer change matriz with 0-1
vec = CountVectorizer(stop_words = "english")
X_train = vec.fit_transform(X_train).toarray()
X_test = vec.transform(X_test).toarray()

In [81]:
X_train


array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0]])



X_train.shape



In [82]:
vec.get_feature_names_out()

array(['ability', 'abke', 'able', ..., 'zespole', 'zom', 'zoming'],
      dtype=object)

In [83]:
#Naive Bayes
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

In [84]:
MultinomialNB()


MultinomialNB()

In [85]:
#score of train dataset 
nb.score(X_train, y_train)

0.9520958083832335

In [86]:
#score test dataset
nb.score(X_test, y_test)

0.820627802690583

In [87]:
nb.predict(vec.transform(['i don\'t like','eat much ram','eat','like']))


array([0, 0, 0, 0])

In [88]:
nb.predict(vec.transform(['love','great solid love important feature','ram','like fast']))

array([1, 1, 0, 1])

In [89]:
df[df['polarity']==1]['review'].sample(10)

665    hamro keyboard fantastic ap mobile write nepal...
569    works great wish suported expandable colapsibl...
635    awesome ap god useful ap fast dowload easy use...
844                                              helpful
824             dont go wal calender turn page month aps
479    makes everything easy slack easy use right wel...
793    awesome browser realy easy use importantly alo...
821                            nepal improving limts gud
662                  word apreciate thank u much founder
810    nice browser doubt firefox one best browsers p...
Name: review, dtype: object

In [90]:
df[df['polarity']==0]['review'].sample(10)

149    able play automatic closing since last two upd...
364    honestly usd love realize honestly stil use ev...
141    frequently resets reset taken stored gone four...
881    game ruined felt like playing awhile imediatel...
876    great game ruined many ads way many ads even f...
323    mark found viber extremely eficient way comuni...
63     notifications working get notify anything new ...
212    update sucks open game anymore damn going war ...
344    wtf keps going ofline automaticaly mesages nev...
650    malayalam font overlaping malayalam fonts over...
Name: review, dtype: object

Save the model 


In [91]:
#filename = '../modelo_final.sav' #use absolute path
pickle.dump(nb, open('../models/modelo_final.sav', 'wb'))
